---
# Fedora CoreOS Kubernetes setup with kubeadm

- name: Fedora CoreOS Kubernetes setup with kubeadm
  hosts: masters:workers
  gather_facts: true

  tasks:
  
  - name: Test connection with ping
    ping:

  - name: Copy fcos-k8s.sh
    ansible.builtin.copy:
      src: /home/p/core/fcos-k8s.sh
      dest: /root/fcos-k8s.sh
      owner: root
      group: root
      mode: '0700'

  - name: Execute fcos-k8s.sh
    raw: /root/fcos-k8s.sh
    register: fcos_k8s_output

  - debug: var=fcos_k8s_output.stdout_lines

  - name: Reboot
    reboot:
      reboot_timeout: 600
      
  - name: Test connection with ping
    ping:


