---

- name: Fedora CoreOS Kubernetes setup with kubeadm
  hosts: master:workers
  roles:
    - remove-python3-for-ansible-service
    - fcos-k8s-sh
      # kubeadm init on master
    - role: kubeadm-init
      when: master in group_names
      # kubeadm join on workers
    - role: kubeadm-join
      when: workers in group_names
