---

- name: Fedora CoreOS Kubernetes setup with kubeadm
  hosts: masters:workers

  roles:
    - remove-python3-for-ansible-service
    - fcos-k8s-sh


- name: Fedora CoreOS Kubernetes init with kubeadm
  hosts: masters

  roles:
    - kubeadm-init
