---
# Fedora CoreOS Kubernetes init with kubeadm

- name: Test connection with ping
  ansible.builtin.ping:

- name: Copy clusterconfig.yaml
  ansible.builtin.copy:
    src: /home/p/fcos-k8s/clusterconfig.yaml
    dest: /root/clusterconfig.yaml
    owner: root
    group: root
    mode: '0700'

- name: Execute kubeadm init
  ansible.builtin.raw: /usr/bin/kubeadm init --config /root/clusterconfig.yaml
  register: kubeadm_output

- name: Print kubeadm init output
  ansible.builtin.debug:
    var: kubeadm_output.stdout_lines

- name: Get kubeadm join command with tokens
  ansible.builtin.set_fact:
    kubeadm_join_command: '{{ kubeadm_output.stdout_lines[-2][:-1] }}{{ kubeadm_output.stdout_lines[-1] | trim }}'

- name: Print kubeadm join command with tokens
  ansible.builtin.debug:
    var: kubeadm_join_command

- name: Create /home/p/.kube directory on ansible node
  remote_user: p
  become: no
  delegate_to: 127.0.0.1
  ansible.builtin.file:
    path: /home/p/.kube
    state: directory
    mode: '0700'

- name: Copy /etc/kubernetes/admin.conf from node1 to /home/p/.kube locally
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: /home/p/.kube

- name: Move /home/p/.kube/192.168.1.201/etc/kubernetes/admin.conf to /home/p/.kube/config on ansible node
  remote_user: p
  become: no
  delegate_to: 127.0.0.1
  ansible.builtin.command:
    cmd: mv /home/p/.kube/192.168.1.201/etc/kubernetes/admin.conf /home/p/.kube/config

- name: Do chmod 700 /home/p/.kube/config on ansible node
  remote_user: p
  become: no
  delegate_to: 127.0.0.1
  ansible.builtin.command:
    cmd: chmod 700 /home/p/.kube/config

- name: Delete with rm -rf /home/p/.kube/192.168.1.201 on ansible node
  remote_user: p
  become: no
  delegate_to: 127.0.0.1
  ansible.builtin.command:
    cmd rm -rf /home/p/.kube/192.168.1.201
