---
# Fedora CoreOS Kubernetes kubeadm join

- name: Test connection with ping
  ansible.builtin.ping:

- name: Get kubeadm join command with tokens from local file
  ansible.builtin.set_fact:
    kubeadm_join_command: "{{ lookup('file', '/home/p/fcos-k8s/kubeadm-join-command.sh') }}"

- name: Print kubeadm join command with tokens
  ansible.builtin.debug:
    msg: "{{ kubeadm_join_command }}"

- name: Execute kubeadm join
  ansible.builtin.command:
    cmd: "{{ kubeadm_join_command }}"
  register: kubeadm_join_output

- name: Print kubeadm join output
  ansible.builtin.debug:
    var: kubeadm_join_output.stdout_lines

- name: Get kubectl get no
  remote_user: p
  become: no
  delegate_to: 127.0.0.1
  ansible.builtin.command:
    cmd: /usr/bin/kubectl get no -owide
  register: kubectl_getno_output

- name: Print kubectl get no output
  ansible.builtin.debug:
    var: kubectl_getno_output.stdout_lines
